### ISSUE TITLE
pip install problem

### ISSUE THREAD

**Issue by i-macdonald** [django-leonardo/django-leonardo#145]
Following instructions at:
https://github.com/django-leonardo/django-leonardo

Command:
python manage.py bootstrap_site --url=http://raw.githubusercontent.com/django-leonardo/django-leonardo/develop/contrib/bootstrap/demo.yaml

fails with:

[14/Mar/2016 13:51:51] INFO [requests.packages.urllib3.connectionpool:207] Starting new HTTP connection (1): raw.githubusercontent.com
[14/Mar/2016 13:51:51] INFO [requests.packages.urllib3.connectionpool:758] Starting new HTTPS connection (1): raw.githubusercontent.com
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(_args, *_options)
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/leonardo_sitestarter/management/commands/bootstrap_site.py", line 37, in handle
    url=url)
  File "/home/iain/src/leonardo2/venv/local/lib/python2.7/site-packages/leonardo_sitestarter/scaffold_web.py", line 133, in create_new_site
    for username, user_attrs in six.iteritems(BOOTSTRAP.pop('auth.User', {})):
AttributeError: 'str' object has no attribute 'pop'

The URL:
http://raw.githubusercontent.com/django-leonardo/django-leonardo/develop/contrib/bootstrap/demo.yaml

gives a "not found" error.

**Comment by michaelkuty** [comment]
Thanks for feedback, I must change readme but you can solve this with new url for bootstrap definition

```
LEONARDO_BOOTSTRAP_URL = 'http://github.com/django-leonardo/django-leonardo/raw/master/contrib/bootstrap/demo.yaml'
```

**Comment by i-macdonald** [comment]
Ahh, that did the trick! Thanks.

In a similar way:
pip install -e git+https://github.com/django-leonardo/django-leonardo@develop#egg=django-leonardo
fails as there is no branch or tag named "develop"
I can put that in a new issue if you want.

**Comment by michaelkuty** [comment]
Fixed in https://github.com/django-leonardo/django-leonardo/commit/c304acb2558af0bb77ca8b836e4588a7e3febe04

**Comment by michaelkuty** [comment]
I've also fix sitestarter package https://github.com/leonardo-modules/leonardo-sitestarter/commit/63f2db1d2f16d385c2afadaaa5f991294a65f781
