### ISSUE TITLE
crispy-forms 1.6 raises error

### ISSUE THREAD

**Issue by michaelkuty** [django-leonardo/django-leonardo#156]
```
  File "/srv/leonardo/sites/kzcars/local/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 117, in get_render
    if helper.template_pack:
AttributeError: 'FormHelper' object has no attribute 'template_pack'
[24/May/2016 16:17:23] WARNING [root:1156] A field should only be rendered once: parent
Traceback (most recent call last):
  File "/srv/leonardo/sites/kzcars/local/lib/python2.7/site-packages/crispy_forms/templatetags/crispy_forms_tags.py", line 117, in get_render
    if helper.template_pack:
AttributeError: 'FormHelper' object has no attribute 'template_pack'
```

**Comment by michaelkuty** [comment]
fixed in @2cec15f586ff61574663d29e2dcc9157f89a76d9
